kind: ConfigMap
apiVersion: v1
metadata:
  name: loki-scripts-admin
  namespace: loki
data:
  threat-intel.rule: |
    name: IP based detection rule
    rules:
    - alert: Malicious IP Detected
      expr: |
        count_over_time({job!=""} |~ "$BLOCK_LIST" [1m]) > 0
      labels:
          severity: critical
      annotations:
          summary: "Malicious IP Detected"
          description: "Malicious IP Detected"
          tenant: $tenant
          topic: acculens
          accuknox: $accuknox
          tool: |
            {{ .Labels.job }}
  threat-intel.sh: |  
    #!/bin/bash
    pushd /scripts
    export BLOCK_LIST=$(curl https://raw.githubusercontent.com/stamparm/ipsum/refs/heads/master/levels/5.txt | grep -v "#" | awk '{print $1}' | sed 's/\./\\\\./g' | paste -sd'|' -)
    TMP_FILE=$(mktemp)
    for ns in $(kubectl get namespace -o name -l env -l tenant | cut -d"/" -f2)
    do
      env=$(kubectl get ns $ns -o jsonpath='{.metadata.labels.env}')
      user=$(echo $ns | sed "s/^tenant-//g")
      export tenant="$env-$user"
      export accuknox=$(kubectl get ns $ns -o jsonpath='{.metadata.labels.accuknox}')
      echo "Processing Tenant=$tenant"
      envsubst < threat-intel.rule > $TMP_FILE
      response=$(curl -H"X-Scope-OrgID: $tenant" -X POST -H "Content-Type: application/yaml" --data-binary "@$TMP_FILE" "$LOKI_GW_SVC/loki/api/v1/rules/threat-intel")
      if [[ "$response" == *'"status":"success"'* ]]; then
        echo "Successfully applied $TMP_FILE"
      else
        echo $response
        echo "ERROR: Loki did not return success for $TMP_FILE"
        echo "Response was: $TMP_FILE"
        exit 1
      fi
    done
    envsubst <  /retreiver-cm-template/loki-rules.yaml > $TMP_FILE
    CMD='.data."loki-rules.yaml" = load_str("'"$TMP_FILE"'")'
    echo "data: " | yq "$CMD" > /tmp/patch.yaml
    kubectl patch cm retriver-cm -n retreiver --patch-file /tmp/patch.yaml
    kubectl rollout restart deployment/retreiver-retriver -n retreiver