
deploymentMode: Distributed

# Disable minio storage
minio:
    enabled: false
ingester:
  replicas: 3
  zoneAwareReplication:
    enabled: false
  chunk_encoding: snappy
querier:
  replicas: 1
  maxUnavailable: 2
  max_concurrent: 4
queryFrontend:
  replicas: 1
  maxUnavailable: 1
queryScheduler:
  replicas: 1
distributor:
  replicas: 1
  maxUnavailable: 2
compactor:
  replicas: 1
indexGateway:
  replicas: 1
  maxUnavailable: 1

bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

singleBinary:
  replicas: 0

ruler:
  replicas: 1
  maxUnavailable: 1

chunksCache:
  enabled: true
  allocatedMemory: 500
  l2:
    allocatedMemory: 500
    enabled: true

resultsCache:
  enabled: true
  allocatedMemory: 500

gateway:
  service:
    type: ClusterIP
  basicAuth:
    enabled: true
