loki:
  rulerConfig:
    alertmanager_url: http://alertmanager.alertmgr.svc.cluster.local:9093
    enable_api: true
    poll_interval: 1m
    evaluation_interval: 1m
    evaluation:
      mode: local
      query_frontend:
        address: dns:///loki-query-frontend.loki.svc.cluster.local:3100
    wal_cleaner:
      min_age: 12h
      period: 24h
    enable_sharding: false
    sharding_algo: by-rule
    ring:
      kvstore:
        store: memberlist
