apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oci-key-oci
  namespace: tenant-go-yubi
  annotations:
    tenant: go-yubi
    collector: oci
    type: oci
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore  # or ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        key.json:  |
          {{ .key | b64dec }}

  data:
  - secretKey: key
    remoteRef:
      key: tenants/go-yubi/oci/oci/key
      property: key
      decodingStrategy: None

