apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oci-logstash-oci
  namespace: tenant-go-yubi
  annotations:
    tenant: go-yubi
    collector: oci
    type: oci
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore  # or ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        pipeline.conf: |
          input {
            kafka{
              bootstrap_servers => "6yhttjlvrqda.streaming.ap-hyderabad-1.oci.oraclecloud.com:9092"
              sasl_jaas_config => "org.apache.kafka.common.security.plain.PlainLoginModule required username='yubigroup/kafka_user/ocid1.streampool.oc1.ap-hyderabad-1.amaaaaaapqylvryas37cowlg6rtj6jqqzig4xydnur2qxkag6yhttjlvrqda'  password='ioFJ}9Et63s94aBG9_p];';"
              security_protocol => "SASL_SSL"
              sasl_mechanism => "PLAIN"
              auto_offset_reset => "earliest"
            }

            http {
              port => 9091
              type => "readiness"
            }
          }

          filter {
              if [type] == "readiness"{
                drop {}
              }
            # Example: If your Pub/Sub messages are JSON, parse them
              json {
                source => "message"
                #target => "parsed_data"
              }

              if [type] == "azure" {
                split {
                  field => "[records]"
                }
                geoip {
                  source => "[records][callerIpAddress]"
                  target => "[geoip]"
                }
                mutate{
                  replace => {"message" => "%{records}"}
                }
              } else if [type] == "oci"{
                geoip {
                  source => "[protoPayload][requestMetadata][callerIp]"
                  target => "[geoip]"
                }
              }
            mutate{
                remove_field =>["[event]", "[message]" ]
              }
          }

          output {
            http {
              url => "http://localhost:8080/loki/api/v1/raw"
              http_method => "post"
              format => "json"
              content_type => "application/json"
            }
          }

  data:
  - secretKey: project
    remoteRef:
      key: tenants/go-yubi/gcp/gcp/info
      property: project
      decodingStrategy: None
  - secretKey: topic
    remoteRef:
      key: tenants/go-yubi/gcp/gcp/info
      property: topic
      decodingStrategy: None
  - secretKey: subscription
    remoteRef:
      key: tenants/go-yubi/gcp/gcp/info
      property: subscription
      decodingStrategy: None
