apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-logstash-cloudwatch
  namespace: tenant-validation
  annotations:
    tenant: validation
    collector: cloudwatch
    type: aws
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore  # or ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        pipeline.conf: |
          input {
            http {
              port => 9090
              codec => line
              user => "{{ .username }}"
              password => "{{ .password }}"
            }
            http {
              port => 9091
              type => "readiness"
            }
          }

          filter {
            if [type] == "readiness"{
              drop {}
            }
            mutate{
              remove_field =>["[event]", "[@version]", "[headers]", "[host]", "[http]", "[url]" ]
            }
          }

          output {
            http {
              url => "http://localhost:8080/loki/api/v1/raw"
              http_method => "post"
              format => "json"
              content_type => "application/json"
            }
          }

  data:
  - secretKey: username
    remoteRef:
      key: tenants/validation/aws/cloudwatch/creds
      property: username
  - secretKey: password
    remoteRef:
      key: tenants/validation/aws/cloudwatch/creds
      property: password
