apiVersion: v1
kind: Service
metadata:
  name: aws-cloudwatch
  namespace: tenant-validation
  annotations:
    tenant: validation
    collector: cloudwatch
    type: aws
spec:
  selector:
    app: aws-cloudwatch
  ports:
  - port: 9090
    targetPort: 9090
    name: tcp
