apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tenant-password
  namespace: tenant-<tenant_id>
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend # AWS, Vault, etc.
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: tenants/<tenant_id>/loki_tenant
        property: username
    - secretKey: password
      remoteRef:
        key: tenants/<tenant_id>/loki_tenant
        property: password