apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-gcp
  namespace: tenant-canary-user
  labels:
    tenant: canary-user
    collector: gcp
    type: gcp
spec:
  selector:
    matchLabels:
      app: gcp-gcp
  template:
    metadata:
      labels:
        app: gcp-gcp
    spec:
      volumes:
        - name:  gcp-alloy-gcp
          secret:
            secretName:  gcp-alloy-gcp
        - name: gcp-logstash-gcp
          secret:
            secretName: gcp-logstash-gcp
        - name: gcp-key-gcp
          secret:
            secretName: gcp-key-gcp
      containers:
      - name: alloy
        image: grafana/alloy:v1.12.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: gcp-alloy-gcp
            readOnly: true
            mountPath: /etc/alloy/
      - name: logstash
        image: public.ecr.aws/k9v9d5v2/admin-tools/crd-collectors/logstash:v1.0.1
        imagePullPolicy: IfNotPresent
        args:
          - "-f"
          - "/configs/pipeline.conf"
        volumeMounts:
          - name: gcp-logstash-gcp
            readOnly: true
            mountPath: /configs/
          - name: gcp-key-gcp
            readOnly: true
            mountPath: /gcp/
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m" 
