apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-logstash-<intergation_id>
  namespace: tenant-<tenant_id>
  annotations:
    tenant: <tenant_id>
    collector: <intergation_id>
    type: azure
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore  # or ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        pipeline.conf: |
          input{
            azure_event_hubs {
              threads => 8
              decorate_events => true
              config_mode => "advanced"
              event_hubs => [
                { 
                  "{{ .eventhubname }}" => {
                  event_hub_connection => "{{ .eventhubconnection }}"
                  storage_connection => "{{ .mutexconn }}"
                  storage_container => "{{.mutexprefix}}-<tenant_id>-<intergation_id>"
                  initial_position => "beginning"
                  #consumer_group => "iam_team"
                  }
                }
              ]
              #consumer_group => "logstash"
              #storage_connection => "DefaultEndpointsProtocol=https;AccountName=example...."
              type => "azure"
            }
            http {
              port => 9091
              type => "readiness"
            }
          }
          filter {
              if [type] == "readiness"{
                drop {}
              }
            # Example: If your Pub/Sub messages are JSON, parse them
            json {
              source => "message"
              #target => "parsed_data"
            }

            if [type] == "azure" {
              split {
                field => "[records]"
              }
              geoip {
                source => "[records][callerIpAddress]"
                target => "[geoip]"
              }
              mutate{
                replace => {"message" => "%{records}"}
              }
            } else if [type] == "gcp"{
              geoip {
                source => "[protoPayload][requestMetadata][callerIp]"
                target => "[geoip]"
              }
            }
            mutate{
                remove_field =>["[event]", "[message]" ]
              }
          }
          output {
            http {
              url => "http://localhost:8080/loki/api/v1/raw"
              http_method => "post"
              format => "json"
              content_type => "application/json"
            }
          }

  data:
  - secretKey: mutexconn
    remoteRef:
      key: mutex/AZURE-STORAGEACCOUNT
      property: primaryconnection
      decodingStrategy: None
  - secretKey: mutexprefix
    remoteRef:
      key: mutex/AZURE-STORAGEACCOUNT
      property: prefix
      decodingStrategy: None
  - secretKey: eventhubconnection
    remoteRef:
      key: tenants/<tenant_id>/azure/<intergation_id>/info
      property: eventhubconnection
      decodingStrategy: None
  - secretKey: eventhubname
    remoteRef:
      key: tenants/<tenant_id>/azure/<intergation_id>/info
      property: eventhubname
      decodingStrategy: None
