apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aws-cloudtrail
  namespace: tenant-sabpaisa
  annotations:
    tenant: sabpaisa
    collector: cloudtrail
    type: aws
    env: in-prod-siem-v2
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName=aws-cloudtrail rewrite=/loki/api/v1/raw"
    nginx.org/auth-type: "basic"
    nginx.org/auth-secret: "htpasswd"
    nginx.org/client-max-body-size: "50m"
spec:
  rules:
    - host: in.siem.v2.accuknox.com
      http:
        paths:
          - path: /in-prod-siem-v2/sabpaisa/788344e36a94bef438eba6f8acfe1284a5f2c816163faa1623507b00/cloudtrail/push
            pathType: Prefix
            backend:
              service:
                name: aws-cloudtrail
                port:
                  number: 9090