apiVersion: v1
kind: Service
metadata:
  name: aws-cloudtrail
  namespace: tenant-sabpaisa
  annotations:
    tenant: sabpaisa
    collector: cloudtrail
    type: aws
spec:
  selector:
    app: aws-cloudtrail
  ports:
  - port: 9090
    targetPort: 9090
    name: tcp
