---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "<vault_addr>"
      path: "<vault_path>"
      version: "v2"
      auth:
        kubernetes:
          # This must match the -path used in the 'vault auth enable' command
          mountPath: "<vault_path>" 
          role: "<vault_role>"
          serviceAccountRef:
            name: "external-secrets"
            namespace: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io