apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: http-<intergation_id>
  namespace: tenant-<tenant_id>
  annotations:
    tenant: <tenant_id>
    collector: <intergation_id>
    type: http
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore  # or ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        config.alloy: |
          loki.source.api "raw_logs" {
            http {
              listen_address = "0.0.0.0"
              listen_port    = 8080
            }

            labels = {
              job = "<intergation_id>",
            }

            forward_to = [loki.write.loki_out.receiver]
          }

          loki.write "loki_out" {
            endpoint {
              url = "http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push"
              basic_auth {
                username = "{{ .username }}"
                password = "{{ .password }}"
              }
            }
          }

  data:
  - secretKey: username
    remoteRef:
      key: tenants/<tenant_id>/loki_tenant
      property: username
      decodingStrategy: None
  - secretKey: password
    remoteRef:
      key: tenants/<tenant_id>/loki_tenant
      property: password
      decodingStrategy: None
