apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-devops-int
  namespace: tenant-qa-test
  annotations:
    tenant: qa-test
    collector: devops-int
    type: http
    env: in-prod-siem-v2
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName=http-devops-int rewrite=/loki/api/v1/raw"
    nginx.org/auth-type: "basic"
    nginx.org/auth-secret: "htpasswd"
    nginx.org/client-max-body-size: "50m"
spec:
  rules:
    - host: in.siem.v2.accuknox.com
      http:
        paths:
          - path: /in-prod-siem-v2/qa-test/c7e5b99450534ac4bde94afe08686ed61963fda0b4df7aa64623f651/devops-int/push
            pathType: Prefix
            backend:
              service:
                name: http-devops-int
                port:
                  number: 8080