apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-logstash-aws
  namespace: tenant-canary-user
  annotations:
    tenant: canary-user
    collector: aws
    type: aws
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore  # or ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        pipeline.conf: |
          input {
            http {
              port => 9090
              type => "aws"
              codec => json_lines
              user => "{{ .username }}"
              password => "{{ .password }}"
            }
            http {
              port => 9091
              type => "readiness"
            }
          }

          filter {
              if [type] == "readiness"{
                drop {}
              }
            # Example: If your Pub/Sub messages are JSON, parse them
              json {
                source => "message"
                #target => "parsed_data"
              }

              if [type] == "azure" {
                split {
                  field => "[records]"
                }
                geoip {
                  source => "[records][callerIpAddress]"
                  target => "[geoip]"
                }
                mutate{
                  replace => {"message" => "%{records}"}
                }
              } else if [type] == "gcp"{
                geoip {
                  source => "[protoPayload][requestMetadata][callerIp]"
                  target => "[geoip]"
                }
              } else if [type] == "aws"{
                if [user_agent][original] and [user_agent][original] =~ /^kube-probe/ {
                  drop { }
                }
                geoip {
                  source => "[sourceIPAddress]"
                  target => "[geoip]"
                }
                mutate{
                  remove_field =>[ "[@version]", "[headers]", "[host]", "[http]", "[url]" ]
                }
              }
            mutate{
                remove_field =>["[event]", "[message]" ]
            }
          }

          output {
            http {
              url => "http://localhost:8080/loki/api/v1/raw"
              http_method => "post"
              format => "json"
              content_type => "application/json"
            }
          }

  data:
  - secretKey: username
    remoteRef:
      key: tenants/canary-user/aws/aws/creds
      property: username
  - secretKey: password
    remoteRef:
      key: tenants/canary-user/aws/aws/creds
      property: password
