apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: htpasswd
  namespace: tenant-achref
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend # AWS, Vault, etc.
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        # The key must be 'auth' for NGINX Ingress Basic Auth
        auth: |
          {{ htpasswd .username .password }}
  data:
    - secretKey: username
      remoteRef:
        key: tenants/achref/loki_tenant
        property: username
    - secretKey: password
      remoteRef:
        key: tenants/achref/loki_tenant
        property: password