---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.accuknox.com:8200"
      path: "siem/in-prod-siem-v2"
      version: "v2"
      auth:
        kubernetes:
          # This must match the -path used in the 'vault auth enable' command
          mountPath: "siem/in-prod-siem-v2" 
          role: "siem-in-prod-siem-v2-external-secrets"
          serviceAccountRef:
            name: "external-secrets"
            namespace: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io