apiVersion: v1
kind: ServiceAccount
metadata:
  name: threat-intel-sa
  namespace: loki

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: retreiver
  name: cm-patcher-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["retriver-cm"]
  verbs: ["patch", "get"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames: ["retreiver-retriver"]
  verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-patch-binding
  namespace: retreiver
subjects:
- kind: ServiceAccount
  name: threat-intel-sa
  namespace: loki
roleRef:
  kind: Role
  name: cm-patcher-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-lister-clusterrole
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-ns-list-binding
subjects:
- kind: ServiceAccount
  name: threat-intel-sa
  namespace: loki
roleRef:
  kind: ClusterRole
  name: namespace-lister-clusterrole
  apiGroup: rbac.authorization.k8s.io