apiVersion: batch/v1
kind: CronJob
metadata:
  name: threat-intel-rule-cron
  namespace: loki
spec:
  schedule: "0 0,12 * * *"
  jobTemplate:
    spec:
      backoffLimit: 3          # Max retries
      ttlSecondsAfterFinished: 600 # Cleanup job 10mins after finishing
      template:
        metadata:
          labels:
            app: threat-intel-rule-job
        spec:
          serviceAccountName: threat-intel-sa
          volumes:
          - name: loki-scripts
            configMap:
              name: loki-scripts-admin
          - name: retreiver-cm-template
            configMap:
              name: retreiver-cm-template
          containers:
          - name: detection-rule
            image: bitnami/kubectl:latest
            command:
            - "bash"
            - "/scripts/threat-intel.sh"
            imagePullPolicy: IfNotPresent
            env:
            - name: LOKI_GW_SVC
              value: "http://loki-ruler.loki.svc.cluster.local:3100"
            volumeMounts:
            - name: loki-scripts
              mountPath: /scripts
              readOnly: true
            - name: retreiver-cm-template
              mountPath: /retreiver-cm-template
              readOnly: true
            resources:
              limits:
                cpu: "200m"
                memory: "100Mi"
              requests:
                cpu: "50m"
                memory: "50Mi"
          restartPolicy: Never