apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aws-aws
  namespace: tenant-seran
  annotations:
    tenant: seran
    collector: aws
    type: aws
    env: validation
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName=aws-aws rewrite=/loki/api/v1/raw"
    nginx.org/auth-type: "basic"
    nginx.org/auth-secret: "htpasswd"
spec:
  rules:
    - host: siem.v2.validation.accuknox.com
      http:
        paths:
          - path: /validation/seran/b4b96e3939a0781a7b050ea16a508e9e851e1d5bc0bf00a15342d4ae/aws/push
            pathType: Prefix
            backend:
              service:
                name: aws-aws
                port:
                  number: 9090