apiVersion: v1
kind: Service
metadata:
  name: aws-cloudtrail
  namespace: tenant-qa-test
  annotations:
    tenant: qa-test
    collector: cloudtrail
    type: aws
spec:
  selector:
    app: aws-cloudtrail
  ports:
  - port: 9090
    targetPort: 9090
    name: tcp
