apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-syslog
  namespace: tenant-qa-test
  labels:
    tenant: qa-test
    collector: syslog
    type: http
spec:
  selector:
    matchLabels:
      app: http-syslog
  template:
    metadata:
      labels:
        app: http-syslog
    spec:
      volumes:
        - name:  http-syslog
          secret:
            secretName:  http-syslog
      containers:
      - name: http-syslog
        image: grafana/alloy:v1.12.2
        imagePullPolicy: IfNotPresent
        args:
        - run
        - /etc/alloy/config.alloy
        - --storage.path=/var/lib/alloy/data
        - --disable-reporting
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
          - name: http-syslog
            readOnly: true
            mountPath: /etc/alloy/
