repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: nginx-ingress
    url: ghcr.io/nginx/charts
    oci: true
  - name: cert-manager
    url: quay.io/jetstack/charts
    oci: true
  - name: accuknox-ecr
    url: public.ecr.aws/k9v9d5v2
    oci: true
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
---
environments:
  default:
    values:
      - storage:
          region: ref+vault://siem/stg/storage/backend/#region
          chunks: ref+vault://siem/stg/storage/backend/#chunks
          admin: ref+vault://siem/stg/storage/backend/#admin
          ruler: ref+vault://siem/stg/storage/backend/#ruler
          accessKeyId: ref+vault://siem/stg/storage/backend/#accessKeyId
          secretAccessKey: ref+vault://siem/stg/storage/backend/#secretAccessKey
      - tenants.yaml
      - canary:
          username: ref+vault://siem/stg/tenants/canary-user/loki_tenant/#username
          password: ref+vault://siem/stg/tenants/canary-user/loki_tenant/#password     
---
releases:
  - name: external-secrets
    chart: external-secrets/external-secrets
    version: 1.2.0
    namespace: external-secrets
  - name: cert-manager
    chart: cert-manager/cert-manager
    version: v1.19.2
    namespace: cert-manager
    values:
    - certmanager/defaults.yaml
  - name: nginx-ingress
    chart: nginx-ingress/nginx-ingress
    version: 2.4.1
    namespace: nginx-ingress
  - name: alertmanager
    chart: prometheus-community/alertmanager
    version: 1.28.1
    namespace: alertmgr
    values:
      - alertmgr/webhook.yaml
  - name: loki
    chart: grafana/loki
    version: 6.45.2
    namespace: loki
    needs:
      - alertmgr/alertmanager
    values:
      - loki/components.yaml
      - loki/loki-common.yaml
      - loki/loki-storage-config.gotmpl
      - loki/loki-canary.gotmpl
      - loki/multi-tenant.gotmpl
      - loki/ruler-config.yaml
  - name: grafana
    chart: grafana/grafana
    namespace: grafana
    values:
      - grafana/grafana-values.yaml
    needs:
      - loki/loki
  - name: rules
    chart: ./rules
    namespace: siem-mgmt
    needs:
    - retreiver/retreiver
  - name: retreiver
    chart: accuknox-ecr/retriver
    version: v1.0.2
    namespace: retreiver
    values:
      - accuknox:
          token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyMjY3Njc0LCJqdGkiOiI1NWY3YWQxM2ZjM2M0YWNjOWI0NjRlYzRiM2ViNDQwMCIsInRlbmFudC1pZCI6MzczMCwiaXNzIjoiY3NwbS5kZW1vLmFjY3Vrbm94LmNvbSJ9.GAPRuIokXu85kmCGGqmvrlH-1Uxtz1ZIC-2fK4YMFiFSxe-T5q8t0PHwsdW3uCZN19lca_CZbwuqx9UX-NdbtWesRgnlKlTuBsQw2OSh6lYfrgIs-90g1cV6yCL7y2dYMtBURF36x6Up8OrN24uWxU5vqz0WD4js5HX68_iMF14M1FX4KzHnWrakSJWu3eaTI9rZ4R8wg5354ZI2YKxTZKYIm63F_Cj8ZR-P9ubpI3Ew9vbm1elagd6sUP-3a2obwBYRq0-6ReUdKO86i9qi_WGesdJPiz2fliRrN9Pr8f-3MFNy23qqlpIX47PUR5XlS9yIyIeAQ_6qMB0WHgA71g
          url: https://cwpp.demo.accuknox.com/webhook/alert
  - name: kustomize
    chart: ./kustomize
    namespace: siem-mgmt
    needs:
     - cert-manager/cert-manager
     - external-secrets/external-secrets
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "sh"
        args:
          - "-c"
          - |
            # Loop until the certificate is found or we hit 30 attempts
            count=0
            until kubectl get certificate logs-tls-secret -n nginx-ingress >/dev/null 2>&1 || [ $count -eq 30 ]; do
              echo "Waiting for ingress-shim to create Certificate..."
              sleep 1
              count=$((count + 1))
            done

            if [ $count -eq 30 ]; then
              echo "Timed out waiting for Certificate object."
              exit 1
            fi

            echo "Certificate found. Annotating..."
            if [ "$(kubectl get certificate logs-tls-secret -n nginx-ingress -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}')" != "True" ]; then
              kubectl annotate certificate logs-tls-secret cert-manager.io/issue-temporary-certificate="true" --overwrite -n nginx-ingress
            fi
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 61.0.0 # Use the latest stable version
    createNamespace: true
    values:
      - prometheus:
          prometheusSpec:
            # Important: This allows Prometheus to find your Loki ServiceMonitors
            serviceMonitorSelectorNilUsesHelmValues: false
            # Persistence for your metrics data on DigitalOcean
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: do-block-storage
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi
      # Disable Alertmanager if you just want metrics for now
        alertmanager:
          enabled: false
        # Grafana is usually already installed with Loki, but you can enable it here
        grafana:
          enabled: false
      - nodeExporter:
          enabled: false
        kubeStateMetrics:
          enabled: false
        kubernetesServiceMonitors:
          enabled: false
        
        # 2. Disable scraping of core K8s components
        kubeApiServer:
          enabled: false
        kubelet:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false

        # 3. Restrict Prometheus to ONLY find your labeled ServiceMonitors
        prometheus:
          prometheusSpec:
            # This tells Prometheus: "ONLY scrape ServiceMonitors with this specific label"
            serviceMonitorSelector:
              matchLabels:
                release: prometheus
            # Disables the default behavior of picking up everything
            serviceMonitorSelectorNilUsesHelmValues: false
        defaultRules:
          enabled: false